module.exports = {
   purge: ["./src/**/*.js"],
   theme: {
      fontFamily: {
         heading: ['"Mulish", sans-serif'],
         // 'display': [''],
         body: ['"Lato", sans-serif'],
      },
      extend: {
         boxShadow: {
            global: "0 2px 24px 0 rgba(97,97,97,0.12)",
         },
         colors: {
            gray: {
               900: "#0C0F1A",
               800: "#0D0D0D",
               700: "#1A1A1A",
               // '600': '',
               // '500': '',
               400: "#808080",
               300: "#979797",
               // '200': '',
               100: "#F8F8F9",
            },
            // primary_dark: '',
            primary: "#FFCB7D",
            primary_light: "#FFD79C",
            // secondary_dark: '',
            // secondary: "",
            // secondary_light: '',
         },
         fontSize: {
            "2xs": ".625rem",
            md: ".9375rem",
            // lg: "1.125rem",
            // xl: "1.25rem",
            // "2xl": "1.5rem",
            // "3xl": "1.875rem",
            "4xl": "2.5rem",
            // "5xl": "3rem",
            "6xl": "3.438rem",
            "7xl": "4rem",
            // "8xl": "",
            // '9xl': "",
            // "10xl": "",
            "mobile-lg": "1rem",
            "mobile-xl": "1.125rem",
            "mobile-2xl": "1.25rem",
            "mobile-3xl": "1.563rem",
            "mobile-4xl": "2rem",
            "mobile-5xl": "2.25rem",
            "mobile-6xl": "1.875rem",
            "mobile-7xl": "2.75rem",
            // "mobile-8xl": "",
            // 'mobile-9xl': "",
            // "mobile-10xl": "",
         },
         maxWidth: {
            "7xl": "77rem",
         },
         spacing: {
            18: "4.5rem",
            22: "5.5rem",
            26: "6.5rem",
            30: "7.5rem",
         },
         width: {
            "50vw": "50vw",
            "75vw": "75vw",
         },
      },
   },
   variants: {
      display: ["responsive", "hover", "focus", "active", "group-hover"],
      width: ["responsive", "hover", "focus", "active", "group-hover"],
      height: ["responsive", "hover", "focus", "active", "group-hover"],
      scale: ["responsive", "hover", "focus", "active", "group-hover"],
      textColor: ["responsive", "hover", "focus", "active", "group-hover"],
      opacity: ["responsive", "hover", "focus", "active", "group-hover"],
      backgroundOpacity: ["responsive", "hover", "focus", "active", "group-hover"],
      backgroundColor: ["responsive", "hover", "focus", "checked"],
   },
   corePlugins: {
      container: false,
   },
};
